import {
  addIconSource,
  archiveIconSource,
  calendarIconSource,
  confirmIconSource,
  closeIconSource,
  colorPickIconSource,
  copyIconSource,
  deleteIconSource,
  disclosureIconSource,
  disclosureDownIconSource,
  dragHandleIconSource,
  editIconSource,
  indeterminateIconSource,
  loadingIconSource,
  menuIconSource,
  nextIconSource,
  previousIconSource,
  priorityMarkerIconSource,
  publishIconSource,
  removeIconSource,
  selectIconSource,
  selectDownIconSource,
  sortIconSource,
  syncIconSource,
  treeDisclosureIconSource,
  uploadIconSource,
  textBoldIconSource,
  textBulletedListIconSource,
  textCodeIconSource,
  textHeadingTwoIconSource,
  textHeadingThreeIconSource,
  textItalicIconSource,
  textLinkIconSource,
  textNumberedListIconSource,
  textParagraphIconSource,
  textQuoteIconSource,
  textStrikethroughIconSource,
  formlessIconSource,
  githubIconSource,
  linkedinIconSource,
  blueskyIconSource,
  threadsIconSource,
  mastodonIconSource,
  xIconSource,
  facebookIconSource,
  instagramIconSource,
  youtubeIconSource,
  vimeoIconSource,
  gravatarIconSource,
  movemberIconSource,
  appleIconSource,
  gitlabIconSource,
  googleIconSource,
  microsoftIconSource,
  npmIconSource,
} from "./sources.ts";

export const builtInIconSources = Object.freeze({
  add: addIconSource,
  archive: archiveIconSource,
  calendar: calendarIconSource,
  confirm: confirmIconSource,
  close: closeIconSource,
  "color-pick": colorPickIconSource,
  copy: copyIconSource,
  delete: deleteIconSource,
  disclosure: disclosureIconSource,
  "disclosure-down": disclosureDownIconSource,
  "drag-handle": dragHandleIconSource,
  edit: editIconSource,
  indeterminate: indeterminateIconSource,
  loading: loadingIconSource,
  menu: menuIconSource,
  next: nextIconSource,
  previous: previousIconSource,
  "priority-marker": priorityMarkerIconSource,
  publish: publishIconSource,
  remove: removeIconSource,
  select: selectIconSource,
  "select-down": selectDownIconSource,
  sort: sortIconSource,
  sync: syncIconSource,
  "tree-disclosure": treeDisclosureIconSource,
  upload: uploadIconSource,
  "text-bold": textBoldIconSource,
  "text-bulleted-list": textBulletedListIconSource,
  "text-code": textCodeIconSource,
  "text-heading-two": textHeadingTwoIconSource,
  "text-heading-three": textHeadingThreeIconSource,
  "text-italic": textItalicIconSource,
  "text-link": textLinkIconSource,
  "text-numbered-list": textNumberedListIconSource,
  "text-paragraph": textParagraphIconSource,
  "text-quote": textQuoteIconSource,
  "text-strikethrough": textStrikethroughIconSource,
  formless: formlessIconSource,
  github: githubIconSource,
  linkedin: linkedinIconSource,
  bluesky: blueskyIconSource,
  threads: threadsIconSource,
  mastodon: mastodonIconSource,
  x: xIconSource,
  facebook: facebookIconSource,
  instagram: instagramIconSource,
  youtube: youtubeIconSource,
  vimeo: vimeoIconSource,
  gravatar: gravatarIconSource,
  movember: movemberIconSource,
  apple: appleIconSource,
  gitlab: gitlabIconSource,
  google: googleIconSource,
  microsoft: microsoftIconSource,
  npm: npmIconSource,
});

export type BuiltInIconKey = keyof typeof builtInIconSources;

export const builtInIconKeys: readonly BuiltInIconKey[] = Object.freeze(
  Object.keys(builtInIconSources) as BuiltInIconKey[],
);

export function isBuiltInIconKey(key: string): key is BuiltInIconKey {
  return Object.hasOwn(builtInIconSources, key);
}

export function resolveBuiltInIconSource(key: string | undefined): string | undefined {
  if (!key) {
    return undefined;
  }

  const normalizedKey = key.trim().toLowerCase();

  return isBuiltInIconKey(normalizedKey) ? builtInIconSources[normalizedKey] : undefined;
}
